### ISSUE TITLE
1st Bug

### ISSUE THREAD

**Issue by Mercydebug** [objection-lol/issues#1]
Well, I was just trying the objections, And I noticed, That rarely when a character says something, The talking sprite is still playing for a couple of seconds.

Don't know if its a serious bug because it only happens rarely, But just wanted to report it.

**Comment by objection-lol** [comment]
Hey,
If you could record it happening that would be helpful.

**Comment by Mercydebug** [comment]
> Hey,
> If you could record it happening that would be helpful.

I will try to get this bug again.

**Comment by Mercydebug** [comment]
I have managed to get the bug again.
https://gyazo.com/083023ae802133b277ace41305d583e9

**Comment by objection-lol** [comment]
This should be fine now, re-open the issue if not.
