### ISSUE TITLE
Arabic language typing is reversed

### ISSUE THREAD

**Issue by Kazero21** [objection-lol/issues#10]
The Arabic language typing on the new website is aligned left which is wrong.

Unlike the old website, the typing was aligned right and it was correct.

![image](https://user-images.githubusercontent.com/68538334/96351968-34300d00-10c8-11eb-8ef6-e6cf4ad4411e.png)

This is wrong

![image](https://user-images.githubusercontent.com/68538334/96351981-588be980-10c8-11eb-91ae-cffdd0e89fe0.png)

This is correct

**Comment by objection-lol** [comment]
Resolved.
