### ISSUE TITLE
Gotcha, Got it and etc. speech bubbles. 

### ISSUE THREAD

**Issue by Mutsuyoshi** [objection-lol/issues#100]
Some characters got unique speech bubbles.
  Example: Apollo Justice's Gotcha
![SoJ_Gotcha%21](https://user-images.githubusercontent.com/74418423/99931415-7b638a80-2d65-11eb-9f6a-82fff3e83037.png)

**Comment by Etalanav** [comment]
Doesn't Apollo already have "Gotcha"?

**Comment by Mutsuyoshi** [comment]
> Doesn't Apollo already have "Gotcha"?

Uh... Well Guess i'll die.
