### ISSUE TITLE
OverRuled Speech bubble for Judge.

### ISSUE THREAD

**Issue by Mutsuyoshi** [objection-lol/issues#102]
![ZamvJ](https://user-images.githubusercontent.com/74418423/99937078-d7360f80-2d75-11eb-9cd4-aec0461da735.png)
Late i'll remake that speech bubble to HD, and find the sound maybe

**Comment by objection-lol** [comment]
its not for this judge.

**Comment by Mutsuyoshi** [comment]
Uh i forgot that it's for Courtney
