### ISSUE TITLE
Video Export

### ISSUE THREAD

**Issue by PhoenixAlwaysRight** [objection-lol/issues#103]
Здравствуйте. Когда я экспортирую видео, как бы я ни старался, оно всё равно заканчивается на одном диалоге во время появления букв. (около 7:00 минуты) Я пытался менять формат, редактировать речь, но видео всё равно экспортируется не до конца, но в предварительном просмотре оно идёт до конца. Само видео состоит из около 250 диалогов, около 9-10 минут, но в mp4 обрывается на 7 минуте. Что мне делать? Всё переделывать заново? Уже измучился.

**Comment by objection-lol** [comment]
Send Email to web.objection.lol@gmail.com with the objection URL

**Comment by PhoenixAlwaysRight** [comment]
I did it. If you didn't see this objection, here is https://objection.lol/objection/729587
(It doesn't export)

**Comment by objection-lol** [comment]
For longer than 7 minutes you must use the recording tool: https://objection.lol/recorder
If you can't, then use OBS with window capture source: https://obsproject.com/
"Export MP4" has 7 minute limit to reduce queue, normally websites don't provide this kind of functionality.
