### ISSUE TITLE
[Bug] I can't login. 

### ISSUE THREAD

**Issue by Mutsuyoshi** [objection-lol/issues#104]
I can not login to my account in objection.lol
I wrote my mail and password properly.

**Comment by objection-lol** [comment]
What's your Email? It may be a Twitter login and you forgot about it, you can also click "forgot password" eitherway:

![image](https://user-images.githubusercontent.com/71948517/99951571-613ea200-2d8f-11eb-9bb7-b46c61c60f8c.png)
