### ISSUE TITLE
Tags don't work in color 

### ISSUE THREAD

**Issue by TalesSouzones** [objection-lol/issues#106]
Hello,i having a problem that the tag don't work.Here is the screenshot
![image](https://user-images.githubusercontent.com/73082481/99985975-63076600-2d8d-11eb-9630-de452c71cdc3.png)

**Comment by Spelunkaria** [comment]
Yeah, unfortunately, tags don't work while they're in a color. I'd say do it like this:

[#/b](Estou sozinho aqui[/#][#p100][#/b] ,tenho nada pra fazer[/#][#p100][#/b] ,nenhum caso pra resolver[/#][#p100][#/b],então vou visitar a Alice.)[/#]

**Comment by objection-lol** [comment]
That's true, there is no tag nesting.
