### ISSUE TITLE
Hotkeys | Горячие клавиши

### ISSUE THREAD

**Issue by SpeedRaser1** [objection-lol/issues#110]
**English**: Function for more productivity! 
For example - I lack the ability to quickly switch between frames.
**Russian**: Функция для большей продуктивности! 
Например - Мне не хватает возможности быстро переключаться между кадрами.

**Comment by objection-lol** [comment]
Hey.
What does "switch between frames" mean?

**Comment by SpeedRaser1** [comment]
> Hey.
> What does "switch between frames" mean?

So I can control these arrows with the keys
![Screenshot_265](https://user-images.githubusercontent.com/66807041/100192058-4a6c8c80-2f02-11eb-8b4f-35373f141831.png)

**Comment by SpeedRaser1** [comment]
Навигация | Navigation:
**Ctrl** + **←** or **→** - Section Moving
**Ctrl** + **1** - Section "Simple Objection"
**Ctrl** + **1** - Section
**Ctrl** + **1** - Section
**Shift** + **F1** - "Help / Information"
**Shift** + **S** - "Save"

**Comment by objection-lol** [comment]
Seen your message too late, some hotkeys are there now, for switch between frames use Q and E.
You can see the rest in Help / Information.
The rest hotkeys can be added later.
