### ISSUE TITLE
Sound Effects

### ISSUE THREAD

**Issue by sunkhaskasis** [objection-lol/issues#111]
I figured I could submit some sound effects that were ripped from the PC version of AAHD. Most of them are just higher quality versions of the existing ones, but I threw in some of the new ones as well.

P.S.: I don't know how you label them, so I just named them either after characters they're associated with or the sound produced.

[sound_effects.zip](https://github.com/objection-lol/issues/files/5591751/sound_effects.zip)

**Comment by objection-lol** [comment]
Got them, thanks.
