### ISSUE TITLE
Mobile view for courtroom

### ISSUE THREAD

**Issue by Pelmeno** [objection-lol/issues#12]
In the mobile version it looks like that
![217BAC09-1043-40AB-814F-02905E472F98](https://user-images.githubusercontent.com/73017018/96364216-5cf4e880-1142-11eb-9cc2-b107e9593ee5.png)
Iphone 6s, i joined to friend’s courtroom from discord

**Comment by objection-lol** [comment]
Hello. Please make sure you're using a modern browser such as Google Chrome.

**Comment by Peekofwar** [comment]
I think Discord uses Chromium, doesn't it?

**Comment by objection-lol** [comment]
Here's what I got clicking the courtroom link from Discord:
![Screenshot](https://user-images.githubusercontent.com/71948517/96659362-71f29700-134f-11eb-81c5-c2df63f09008.jpg)

I don't think Discord can use Chrome if you don't have it installed, if anyone has the same problem as OP please confirm.

**Comment by Peekofwar** [comment]
> I don't think Discord can use Chrome if you don't have it installed, if anyone has the same problem as OP please confirm.

No, I'm not talking about Google Chrome... I'm talking about Chromium (which Google Chrome is based on or something). Pretty sure Discord uses a Chromium-based web viewer. 

https://www.reddit.com/r/discordapp/comments/4z5tmb/does_discord_use_chromium/

**Comment by Peekofwar** [comment]
Can confirm I also got a black screen in the player when I joined a courtroom through Discord's web-viewer, however, after sending a character message, Phoenix showed up on-screen.

**Comment by objection-lol** [comment]
@Peekofwar The black screen is intended, it's the default background if no one has sent any message yet.

**Comment by Peekofwar** [comment]
Oh, wait... lol - I forgot what the original issue was....

**Comment by Emily6435** [comment]
I have this bug as well, Iphone 11

**Comment by objection-lol** [comment]
Hi,
This has been stale for a while, as we cannot reproduce the issue we are not able to fix it.
If there is any helpful info on how to reproduce this problem re-open the issue. Thank you.
