### ISSUE TITLE
Cannot set a custom color with sound effects inside.

### ISSUE THREAD

**Issue by Audacity0001** [objection-lol/issues#120]
Hello again c:
I'm sorry for being annoying, but, I got a little issue: Basically, i wanna send this message with the Green color using sound effects, however, if I do so, it'll look like this: 
![Schermata 2020-11-26 alle 23 13 57](https://user-images.githubusercontent.com/24767392/100394684-578e9600-303e-11eb-8318-60ec464142df.png)

How can I solve this? Many thanks c:

**Comment by 21memes21** [comment]
you can't have other tags inside colors
if you want tags you could do something like
[/g]hello,[/#] [#p500] [/g]and welcome to the courtroom[/#]

**Comment by PhoenixRight** [comment]
[#bgs27][#/g]C[/#][#bgs27][#/g]o[/#][#bgs27][#/g]d[/#][#bgs27][#/g]c[/#] etc.
Write according to this scheme

**Comment by Audacity0001** [comment]
Thank you so much for the help. 😄

**Comment by objection-lol** [comment]
This seems solved, thanks.
