### ISSUE TITLE
Move character on scene

### ISSUE THREAD

**Issue by Mutsuyoshi** [objection-lol/issues#121]
I'd like to be able to move the character up/down/side in the scene, and to be able to save the settings for each follow.

**Comment by maxdevgithub** [comment]
That would work best for custom characters

**Comment by maxdevgithub** [comment]
for example when the defense attorney is centered, and you need the sprite to the left just use X and Y axis character positioning

**Comment by objection-lol** [comment]
> for example when the defense attorney is centered, and you need the sprite to the left just use X and Y axis character positioning

The problem with X/Y offset is its not responsive, for mobile it will look very off.

**Comment by MadLeroy** [comment]
Yes! I don't really care if it looks off on mobile, I definitely want an AAI maker for objection.lol

**Comment by objection-lol** [comment]
> Yes! I don't really care if it looks off on mobile, I definitely want an AAI maker for objection.lol

Adding AAI characters would be enough, there is no need to offset them, and it would be fine for mobile as wel.

Anyway, closing this as its likely not going to be implemented, you can use transparent background for your custom characters just like the preset characters.
