### ISSUE TITLE
[suggestion] more then one character on scene

### ISSUE THREAD

**Issue by Mutsuyoshi** [objection-lol/issues#122]
Just like in AAI

**Comment by maxdevgithub** [comment]
> Just like in AAI

I dont think this will work well
![ummm](https://user-images.githubusercontent.com/58821795/100789515-3a334080-341f-11eb-9fdd-3203e4dedd2c.PNG)

**Comment by objection-lol** [comment]
Hi,
Likely not going to happen, thanks for the suggestion though.
