### ISSUE TITLE
Bigger / smaller text

### ISSUE THREAD

**Issue by Spelunkaria** [objection-lol/issues#123]
We could have a tag that lets you make the text bigger or smaller to emphasize different situations.

**Comment by PavelChitaylo** [comment]
I don't think this is one of the in-game features

**Comment by Mutsuyoshi** [comment]
> I don't think this is one of the in-game features.

Maybe it will be compatible with custom textboxes

**Comment by Spelunkaria** [comment]
That's the thing! It doesn't matter if it's a game feature or not, like for
instance, are custom backgrounds a feature of the games?

Il lun 30 nov 2020, 17:49 PavelChitaylo <notifications@github.com> ha
scritto:

**Comment by PavelChitaylo** [comment]
It would be weird if this website turned into Attorney Online-like thing.

**Comment by Mutsuyoshi** [comment]
> It would be weird if this website turned into Attorney Online-like thing.

I'm sorry, but we tired to see in game characters. That is too boring. And we wanted to see our OCs in our objections.

**Comment by maxdevgithub** [comment]
> It would be weird if this website turned into Attorney Online-like thing.

Someone suggested roleplay courtroom mode which is kinda like AAO, however people make funny stuff like "Homeless" Phoenix Wright as a lawyer, people can add fanmade animations, OC's, sometimes even GMod characters on the bright side. objection.lol is mainly used for funny memes

**Comment by objection-lol** [comment]
Adding new features would not remove the old ones, you can still use the preset characters after the option to add custom characters is done, and there will be option to disable custom characters in courtroom.

**Comment by objection-lol** [comment]
Hi,
Likely not going to be implemented, thanks for the suggestion though.

**Comment by Spelunkaria** [comment]
Aw, bummer. Thanks for the answer though!
