### ISSUE TITLE
Issue with custom music and sounds.

### ISSUE THREAD

**Issue by TApocEK111** [objection-lol/issues#124]
Recently, I was trying to add custom sound. Unfortunately I failed. Every time I pushed "ADD" button I faced message wich was telling me that my URL was invalid. I tried various formats, different sources but nothing helped. 

Well, it would be really great if someone can give me a sample link.

Thanks in advance.

**Comment by 21memes21** [comment]
i personally upload the files to vocaroo and after the uploading is done you have to right click on the download button and then click copy link address (hope this helped)

**Comment by TApocEK111** [comment]
> i personally upload the files to vocaroo and after the uploading is done you have to right click on the download button and then click copy link address (hope this helped)

Thank you so much.
