### ISSUE TITLE
Ability To Change Between Old And New Backrounds

### ISSUE THREAD

**Issue by 21memes21** [objection-lol/issues#125]
In short:The ability to change to the old court backgrounds and the new ones
It is perfectly understandable if it doesn't get added

**Comment by RichardWell56** [comment]
If you realy want, add this to your custom backgrouns:
![Objection!](https://user-images.githubusercontent.com/73120927/100579633-30a9bb80-32ed-11eb-80f8-a61f0875fc40.png)
![judge-bg](https://user-images.githubusercontent.com/73120927/100579711-5c2ca600-32ed-11eb-8da0-1083cc56e960.png)
![Objection! (4)](https://user-images.githubusercontent.com/73120927/100579748-6ea6df80-32ed-11eb-9ea2-20e68ba67e13.png)
![Objection! (3)](https://user-images.githubusercontent.com/73120927/100579773-7a92a180-32ed-11eb-9b2a-0a205ad1bf6c.png)
![Objection! (1)](https://user-images.githubusercontent.com/73120927/100579789-81b9af80-32ed-11eb-9295-dfd8b8285643.png)

**Comment by 21memes21** [comment]
the prosecution's side is missing but i guess this does for now

**Comment by objection-lol** [comment]
> the prosecution's side is missing but i guess this does for now

You can just flip the defense background and desk horizontally 
![100579748-6ea6df80-32ed-11eb-9ea2-20e68ba67e13](https://user-images.githubusercontent.com/71948517/100594720-1bdc2080-330b-11eb-8a2f-6acd010b2f8a.png)
to have the prosecution side.
![100579773-7a92a180-32ed-11eb-9b2a-0a205ad1bf6c](https://user-images.githubusercontent.com/71948517/100594893-4d54ec00-330b-11eb-9bfc-08aa46cd4592.png)

**Comment by 21memes21** [comment]
thank you
you can close this if it isn't going to be added as pre existing backround

**Comment by objection-lol** [comment]
Unfortunately not

**Comment by maxdevgithub** [comment]
Where is AJ Turnabout Sucession 7 years ago background?
