### ISSUE TITLE
Custom Characters

### ISSUE THREAD

**Issue by MadLeroy** [objection-lol/issues#126]
When will the custom characters be a thing? Also, is there a way to watch other people's trials without a link or code? someone barged into my trial recently that I didn't invite...

**Comment by objection-lol** [comment]
It's coming next, before the end of this year.
Anyone with the link can join, maybe one of the people you invited shared the link.

**Comment by MadLeroy** [comment]
I only invited one person, and he definitely didn't invite someone else...

**Comment by MadLeroy** [comment]
also, do you need any help maintaining the site? I would absolutely love to become an objection.lol developer...

**Comment by Mutsuyoshi** [comment]
If you know something about js or etc., you maybe can help with developing

**Comment by Mutsuyoshi** [comment]
Anyway i wanted to ask. How it cloud works?

**Comment by MadLeroy** [comment]
idk?
what do you mean?

**Comment by MadLeroy** [comment]
did you mean how COULD it work? as in the custom characters?

**Comment by Mutsuyoshi** [comment]
> did you mean how COULD it work? as in the custom characters?

Yes, i meant it. Your Russian servant know English too badly, sorry.

**Comment by MadLeroy** [comment]
I'm pretty sure you would just put the sprite gif into the website, but idk
