### ISSUE TITLE
[Feature] Loading proof from PC and not only from websites.

### ISSUE THREAD

**Issue by Audacity0001** [objection-lol/issues#130]
Hello, 
This is a simple feature request, I would like to suggest the ability to load proof from the PC, and not only from a website. 

I tried to use Imgur to load my proof, however, it doesn't work. :/ 

Thanks and have a nice day. :)

**Comment by MadLeroy** [comment]
Just use [postimages.org](url)

Copy the direct link, then paste it into the evidence link option on objection.lol

Hope this helped!

**Comment by MadLeroy** [comment]
I know my solution doesn't address your problem, but this is the best solution I have. Sorry.

**Comment by Audacity0001** [comment]
This helped me a lot, thank you so much! :)

**Comment by MadLeroy** [comment]
Happy to help!
