### ISSUE TITLE
How to assign gallery sprites ?

### ISSUE THREAD

**Issue by Mehmet-dev** [objection-lol/issues#136]
objection.lol/maker has a gallery sound effect but not a gallery sprite .

**Comment by objection-lol** [comment]
You can assign gallery sprites using the frame action Gallery: Assign a character.
It's only visible after you preview the frame.

**Comment by Mehmet-dev** [comment]
oh thanks. didnt know that.

**Comment by Mehmet-dev** [comment]
can you please explain it more I couldnt achieve it ?

**Comment by Mehmet-dev** [comment]
can you help please ? @objection-lol I cant do it.
