### ISSUE TITLE
Pre-wrap text

### ISSUE THREAD

**Issue by Lucretiel** [objection-lol/issues#137]
When scrolling text is being rendered in a scene, it's a bit distracting when a long word jumps to the next line as it grows longer during the render. Would it be possible to pre-flow the text so that all the words are in their final positions before the text starts appear?

Example: https://objection.lol/objection/820006

**Comment by HazmatDrone** [comment]
See #112

**Comment by Lucretiel** [comment]
Oh, yup, that's a duplicate
