### ISSUE TITLE
[Suggestion] Enable GitHub Discussions

### ISSUE THREAD

**Issue by HazmatDrone** [objection-lol/issues#138]
GitHub recently added Discussions, which can be enabled in the repository settings. It's meant to be a sort of forum of sorts, for things that shouldn't be made issues.

The discussions page would be helpful for general Q&A for people needing help with doing certain things in objection.lol, as well as a place for people to show off their objections, or just discuss things in general.

**Comment by objection-lol** [comment]
Maybe, it has to be either Discord or Discussions for easier maintenance.

**Comment by HazmatDrone** [comment]
GitHub Discussions certainly *feels* nicer as a proper structured forum, but of course the average person doesn't use GitHub; that's only something us more savvy users are on. IMO it might be worth trialing both side by side?

**Comment by objection-lol** [comment]
Its enabled.
