### ISSUE TITLE
Animation

### ISSUE THREAD

**Issue by PhoenixRight** [objection-lol/issues#14]
Hello dear developers! I wish you could add this animation for Redd White! Thanks in advance!)
![Animation_014](https://user-images.githubusercontent.com/73066569/96369328-eec01e00-1161-11eb-9e59-9be7a39a6715.gif)

**Comment by objection-lol** [comment]
It has been added.

**Comment by PhoenixRight** [comment]
> It has been added.

Yeah, i see, thx!!!
