### ISSUE TITLE
[BUG] White Flash is Gray in Dark Theme

### ISSUE THREAD

**Issue by Peekofwar** [objection-lol/issues#16]
I've noticed my screen flashing black, and I just realized it's because there's no white rectangle behind the player; just a dark-gray background.

**Comment by objection-lol** [comment]
It may not be favorable to have a white flash in a dark theme, will check how it turns out to be.

**Comment by objection-lol** [comment]
Hello.
If you use both shake + flash at the same time then the white rectangle behind will show during the shake. Shaking the white rectangle along with the player also did not look well too.

**Comment by Peekofwar** [comment]
> Hello.
> If you use both shake + flash at the same time then the white rectangle behind will show during the shake. Shaking the white rectangle along with the player also did not look well too.

Maybe it could be an optional thing then.

**Comment by objection-lol** [comment]
The flash is now white in the dark theme.
