### ISSUE TITLE
Edit Scene Dialog Dismiss when Clicking Outside Box

### ISSUE THREAD

**Issue by Peekofwar** [objection-lol/issues#17]
It would be nice, and more consistent with the rest of the interface if clicking outside of the Edit Scene dialog box would automatically dismiss the dialog.

![0001](https://user-images.githubusercontent.com/10189526/96373550-10011a00-1122-11eb-9939-786fa71563fa.jpg)

**Comment by objection-lol** [comment]
Hey.
If it closes by clicking outside then you'd lose the ability to edit multiple frames without having to re-open.
From your screenshot, you can click the thumbnails for frames 3 to 7 and the dialog would remain open so you can edit quicker.
You can also close/open the dialog by pressing C on your keyboard.

**Comment by Peekofwar** [comment]
Edit multiple frames? I was unaware you could do this.

**Comment by Peekofwar** [comment]
> Hey.
> If it closes by clicking outside then you'd lose the ability to edit multiple frames without having to re-open.
> From your screenshot, you can click the thumbnails for frames 3 to 7 and the dialog would remain open so you can edit quicker.
> You can also close/open the dialog by pressing C on your keyboard.

You could program it so that it will only close the dialog box if you both click off, AND are not clicking on a frame thumbnail.

Something like `if isOutOfBounds and not isFrameThumbnail then closeDialog() end`

**Comment by objection-lol** [comment]
The behavior above has been implemented, it will close on click outside unless you're clicking another thumbnail.
