### ISSUE TITLE
Option/Tag to Remove Character from Scene

### ISSUE THREAD

**Issue by Peekofwar** [objection-lol/issues#18]
It would be cool if you could remove a character from the scene, which would mean they would not appear in the gallery view... Say we wanted the judge to take a bathroom break or something, but we also wanted to show the gallery view again... We would need a way to tell the Objection player to remove the character from the scene so that it doesn't show the judge in the chair.

**Comment by objection-lol** [comment]
It's possible now through frame actions.
Gallery: Remove a character
