### ISSUE TITLE
[BUG] Hotkeys Interfere with Typing in Courtroom

### ISSUE THREAD

**Issue by Peekofwar** [objection-lol/issues#20]
This was an issue with the old courtroom as well where I'll be typing in the text box below the preview, and suddenly the edit box is unfocused and my character changes.

**Comment by objection-lol** [comment]
Shift + Space deselects the text box. You can use caps lock to upper case messages.

**Comment by Peekofwar** [comment]
> Shift + Space deselects the text box. You can use caps lock if you want to upper case whole messages easily.

The problem is that I'm activating that hotkey--which I didn't even know existed--accidentally. Most likely in situations where I'm entering a parenthesis and then a capital letter for the beginning of a sentence. Eg: `( I can't believe this is happening )`

**Comment by objection-lol** [comment]
I will change the shortcut to be CTRL + Space, that should solve the problem.

**Comment by objection-lol** [comment]
Changed to Ctrl + Space.
