### ISSUE TITLE
[BUG-Courtroom] Text is Deselected when Text Color Menu is Opened

### ISSUE THREAD

**Issue by Peekofwar** [objection-lol/issues#21]
I am struggling to set the color to the blue preset, as every time I open the color menu above the Courtroom text edit box, the text I am trying to add the tag to is deselected, and the tag refuses to insert.

**Comment by objection-lol** [comment]
In the courtroom, you don't color tag or text speed tag like the Maker page, you can set your text color (press the Set button) and it will automatically color your entire message, this is easier for real-time messages.
