### ISSUE TITLE
SHIFT+Mousewheel to Horizontally Scroll Avatar Poses

### ISSUE THREAD

**Issue by Peekofwar** [objection-lol/issues#22]
I am very use to using SHIFT+mousewheel to scroll sideways in apps and websites. It feels strange to have to click and drag to scroll through the poses in the courtroom.

**Comment by objection-lol** [comment]
Hi,
This has been attempted and the result wasn't great, and so it won't be implemented.

**Comment by Peekofwar** [comment]
> Hi,
> This has been attempted and the result wasn't great, and so it won't be implemented.

What went wrong? Just curious.
