### ISSUE TITLE
[SUGGESTION-Accounts] Evidence Locker

### ISSUE THREAD

**Issue by Peekofwar** [objection-lol/issues#23]
Now that we can sign-in and edit our existing Objections (created with the account), it would be convenient if we could review our uploaded evidence, edit, and/or remove them. In the Courtroom and Objection maker, there could be an option to insert from Evidence Locker.

Side-note: Would be cool if we could attach an icon to the same evidence ID, so when requesting an icon from the evidence ID, it would specifically grab the icon file if it exists, and vise versa with the full-screen evidence file; else it grabs whichever file is available.

**Comment by objection-lol** [comment]
If you add a custom evidence, music, or sound while logged in, the "name" box will remember it and you can choose it again as autocomplete:

![image](https://user-images.githubusercontent.com/71948517/96408014-4a82b980-11eb-11eb-89f5-cf44bd5b20ee.png)

There can never be an edit option, this can be improved but for now, it will be left as it is.
