### ISSUE TITLE
Animations

### ISSUE THREAD

**Issue by PhoenixRight** [objection-lol/issues#25]
Hello dear developers! It's me, again. I would like you to add these two Breakdowns for Frank Sahwit and this animation for Phoenix only in HD
![sahwit-toss](https://user-images.githubusercontent.com/73066569/96440304-72384880-1210-11eb-89ad-2b5d3c9ff5b2.gif)
![sahwit-break](https://user-images.githubusercontent.com/73066569/96440375-8da35380-1210-11eb-8f39-501c7247fc67.gif)
![Animation_021](https://user-images.githubusercontent.com/73066569/96440443-a6136e00-1210-11eb-9a4b-1a0df6c34c99.gif)

**Comment by objection-lol** [comment]
Hi,
For future requests please use the newly added pinned issue.
