### ISSUE TITLE
Godot animations

### ISSUE THREAD

**Issue by Cl0ckHvH** [objection-lol/issues#26]
Hello developer, can You add this two animations?
![godot-catch steaming](https://user-images.githubusercontent.com/62774712/96443203-f391da00-1214-11eb-9453-a2aa404f77f4.gif)
![godot-break(a)](https://user-images.githubusercontent.com/62774712/96443080-bb8a9700-1214-11eb-911d-8853985111f5.gif)

**Comment by objection-lol** [comment]
Hi,
For future requests please use the newly added pinned issue.
