### ISSUE TITLE
Force/Replay Speech Bubble Option

### ISSUE THREAD

**Issue by Peekofwar** [objection-lol/issues#28]
If would be cool if you could tell the player to forcibly replay a speech bubble, such as having the Judge pound the gavel after already appearing on-screen without flipping the frame or moving to a different character first.

It would also be cool if you could specifically call a character's Speech Bubble, like to call Edgeworth's _Objection_ bubble without switching to him.... like those scenes where a character raises an objection, but it flicks to every other character in the room with a dramatic sound before revealing who raised it.

**Comment by objection-lol** [comment]
This is possible now by using the "off-screen speech bubble" action + flip side.
