### ISSUE TITLE
Text

### ISSUE THREAD

**Issue by VovaGamesChips** [objection-lol/issues#3]
A friend of mine had the following bug: The text repeated letters several times, although I wrote legible text. Perhaps this is due to her lags, because she lagged madly when we tested.

(And yes, if there are mistakes, then I'm sorry. I used google translate.)
![unknown (1)](https://user-images.githubusercontent.com/55021547/96291449-b3eaa880-0ff0-11eb-9935-49778df6daaa.png)

**Comment by objection-lol** [comment]
It could be because of lag, since I can't reproduce it at will it will be closed for now.
