### ISSUE TITLE
add evidence/music/sound without url

### ISSUE THREAD

**Issue by TalesSouzones** [objection-lol/issues#30]
I suggest adding evidence/music/sound directely from your computer,because adding a evidence/music/sound with a url it's hard.

**Comment by objection-lol** [comment]
Hello.
That's indeed true, however, the server is too small to handle that.
Moreover, if you are signed in with your account the website will remember the custom music, sounds, and evidence that you have added previously and it will show them as auto-complete:
![image](https://user-images.githubusercontent.com/71948517/96656917-83d13b80-1349-11eb-9380-8b7596ac0dbe.png)
