### ISSUE TITLE
Custom bubbles maker

### ISSUE THREAD

**Issue by Cl0ckHvH** [objection-lol/issues#31]
It would be cool to make custom bubbles and custom voice for there
<img width="2645" alt="Bubble-font-2x Bmatsantos" src="https://user-images.githubusercontent.com/62774712/96768036-01e32000-13e6-11eb-813a-601a70d3f94d.png">

**Comment by objection-lol** [comment]
Hi,
Custom speech bubbles will come in the future eventually, it's not a high priority right now.
