### ISSUE TITLE
Gallery Sprites Overlay Evidence

### ISSUE THREAD

**Issue by Peekofwar** [objection-lol/issues#32]
When fullscreen evidence is shown when in the Gallery view, the gallery character sprites appear over top the evidence layer. This was an issue on the old Objection maker too.
![image](https://user-images.githubusercontent.com/10189526/96793817-eb22d600-13b1-11eb-8fd3-3e6f279c4101.png)

**Comment by TalesSouzones** [comment]
Hey,how you put letters on the middle?

**Comment by VovaGamesChips** [comment]
He used this symbol: "⠀".

**Comment by Peekofwar** [comment]
> Hey,how you put text on the middle?

`[#ts1][#evd18798]
[#/c000000]----------------[/#][#ts40][#/g]October 22, 1:02 PM[/#][#ts1][#/c000000]---------[/#]
[#/c000000]-----------------------------[/#][#ts40][#/g]District Court[/#][#ts1][#/c000000]------------[/#]
[#/c000000]-----------------------------[/#][#ts40][#/g]Courtroom No. 4[/#][#p1500][#evdh]`

**Comment by objection-lol** [comment]
This will be kept as it is, as a user of the Maker page you can avoid this, or even use it, its a feature!
