### ISSUE TITLE
New frames

### ISSUE THREAD

**Issue by beeflol** [objection-lol/issues#33]
I suggest add Klavier and Apollo damage frames
![AltruisticDesertedCrayfish-max-1mb](https://user-images.githubusercontent.com/73265534/96895797-2df0b680-1463-11eb-9b23-13359f27655d.gif) 

![apollo-ohshit](https://user-images.githubusercontent.com/73265534/96896031-73ad7f00-1463-11eb-95c0-9b878f642b07.gif)

**Comment by objection-lol** [comment]
Please post these requests in the pinned issue.
