### ISSUE TITLE
Problems with the new version of the site

### ISSUE THREAD

**Issue by DarkWanderer1** [objection-lol/issues#35]
Здравствуйте у меня есть две проблемы с  разделом "Зал Суда".
Первая проблема заключается в непрекращающейся тряске экрана если мой браузер развернут.
Вторая проблема заключается в никнеймах. Дело в том что раньше никнейм что вводился  в имя пользователя в настройках , отображался в речи персонажей, на данный момент такого не происходит и на всех персонажей отображается один никнейм Феникс.
Пожалуйста, если сможете исправьте эту проблему, очень хотелось  чтобы выбранные никнеймы оторажались на самих персонажах.
Спасибо за прочтение

**Comment by AQ206** [comment]
bruh did microsoft buy the whole site

**Comment by heeeyohu** [comment]
[EN Translation]
Hello, I have two issues with "Courtroom" page.
The first problem is incessant screen shaking while my browser is being hided. The second problem is about nicknames. The fact is that earlier the nickname that was entered into the username in the settings was displayed in the speech of the characters, at the moment this does not happen and one nickname Phoenix is displayed on all characters.
If you could, please fix these issue, I really wanted the selected nicknames to be reflected on the characters themselves.
Thanks for reading

**Comment by DarkWanderer1** [comment]
> [EN Translation]
> Hello, I have two issues with "Courtroom" page.
> The first problem is incessant screen shaking while my browser is being hided. The second problem is about nicknames. The fact is that earlier the nickname that was entered into the username in the settings was displayed in the speech of the characters, at the moment this does not happen and one nickname Phoenix is displayed on all characters.
> If you could, please fix these issue, I really wanted the selected nicknames to be reflected on the characters themselves.
> Thanks for reading

**Comment by DarkWanderer1** [comment]
Thank you, I did not accidentally send a translation, but the original text.
But the first problem is not that my images in the courtroom shake when I hide the browser, but on the contrary, my site screen shakes when it is maximized. When it is as if compressed, this does not happen

**Comment by DarkWanderer1** [comment]
And just accidentally closed the problem

**Comment by DarkWanderer1** [comment]
I must add that a similar problem exists only in the chrome browser

**Comment by objection-lol** [comment]
Hi,
Not sure what do you mean by a screen shaking problem when the browser is hidden.
As for nicknames, please look at this:

![1](https://user-images.githubusercontent.com/71948517/97033800-9081a980-156c-11eb-8626-a85312ef4f21.gif)

Does it not work for you?

**Comment by omnibones** [comment]
uhm I tried to use the courtroom with my friend and it lets me make one, but whenever I try to set my username it doesn't save what I'm typing and the text goes away after i click off the text box. also, i can't send any chats at all (I can type stuff and set poses but the chats don't go through or something and the little window remains black) and the user counter stays on 0. I was really sad when I saw it wasn't working so i literally made an entire account so I could tell you this. 
Thank you for your time!

**Comment by omnibones** [comment]
(also im using chrome)

**Comment by objection-lol** [comment]
@omnibones This means the connection to the courtroom server was not established for some reason, does this happen all the time or was your internet down for some time?

**Comment by omnibones** [comment]
@objection-lol it happened to me multiple times in a row, and there was nothing wrong with my internet (at least im pretty sure,,,)
it happened before the website was switched over, too, I just used the old one from the previous site because that one worked for me

**Comment by omnibones** [comment]
@objection-lol it happened to my friend too, he told me it wasn't working for him either

**Comment by DarkWanderer1** [comment]
As for the nickname, it doesn't work, that's why I'm writing about the problem.
And the shaking of the screen (the browser itself) occurs when Chrome is in full screen mode. Sorry for the confusion, I did not formulate my thoughts correctly.
Also in Chrome, when I enter the courtroom, it shows me that there are no users in the courtroom.
The only thing all problems disappear is when I change my browser to Internet Explorer, but mostly I use Chrome because I find it rather inconvenient to switch between browsers. But if the problem cannot be fixed, you have to accept

**Comment by objection-lol** [comment]
Hi,
This has been stale for a while, as we cannot reproduce the issue we are not able to fix it.
If there is any helpful info on how to reproduce this problem re-open the issue. Thank you.
