### ISSUE TITLE
Strange Klavier thing

### ISSUE THREAD

**Issue by LLightNiNGMoNSTeR** [objection-lol/issues#37]
Hello! There's a thing with HD Klavier - there's an annoying line on the screen. Also not an issue - we wait for Apollo HD model)))

**Comment by beeflol** [comment]
Yeah this happen me when i export it to video
![20201023_175147](https://user-images.githubusercontent.com/73265534/97053046-8a81cd80-1558-11eb-93f8-4e0756de5d87.jpg)

**Comment by objection-lol** [comment]
@LLightNiNGMoNSTeR If the sprites don't exist we can't add it, unfortunately, there no ripping done here.

**Comment by objection-lol** [comment]
There's no line on the website, it's only happening when recording/exporting, strange is the right word.

**Comment by objection-lol** [comment]
If you flip his position there is no line in the video:
![image](https://user-images.githubusercontent.com/71948517/97293296-8b1eaa80-185d-11eb-9413-b1c7ca8b67ea.png)

**Comment by objection-lol** [comment]
This is no longer happening.
