### ISSUE TITLE
Preview the scene visual bugs

### ISSUE THREAD

**Issue by NikiNin7044** [objection-lol/issues#4]
Hello, tried the test site and found out some interesting visual bugs. So, with the scene preview feature we're now able to see the character, text bubble and the pose on the editing frame screen
But once we create a new frame, the pose resets, but the preview doesn't. So this might happen (The pose on the preview is clearly not the "stand" pose)
![IMG_20201016_210552](https://user-images.githubusercontent.com/72994640/96296456-f9f73a80-0ff7-11eb-9bff-321fbd115a99.jpg) 
![IMG_20201016_210603](https://user-images.githubusercontent.com/72994640/96296455-f95ea400-0ff7-11eb-8e1b-14babc33ffef.jpg)
Also I tried to switch from "Yell" pose to other poses and this happened
![IMG_20201016_210624](https://user-images.githubusercontent.com/72994640/96296454-f82d7700-0ff7-11eb-8dc3-28beba6012cf.jpg)

**Comment by objection-lol** [comment]
Are you sure it wasn't because of lag? If the connection is slow it takes time to download the pose/background/etc...

**Comment by NikiNin7044** [comment]
100% sure it wasn't because of lag, as just simply changing poses didn't take more than a second and showed the updated scene immediately.
On a new version of the site the pose doesn't reset on the new frame and the problems are resolved, so, I think, this issue can be closed
