### ISSUE TITLE
objection process finished after a queue, but video gives an error.

### ISSUE THREAD

**Issue by HargoTheVyonder** [objection-lol/issues#41]
please fix it.

**Comment by HargoTheVyonder** [comment]
- [ ] fixed?

**Comment by objection-lol** [comment]
Hello.
Please provide the objection URL to have a look at it.

**Comment by HargoTheVyonder** [comment]
https://objection.lol/objection/612716

**Comment by HargoTheVyonder** [comment]
the file was corrupted

**Comment by objection-lol** [comment]
Here it is, there's nothing wrong with it. If it doesn't open use VLC media player,
https://drive.google.com/file/d/1H_EzWQWWkFOuC_TkXQkvxBgrhfLio8GK/view?usp=sharing

**Comment by HargoTheVyonder** [comment]
Thanks, i will have to upload it to YouTube.

**Comment by HargoTheVyonder** [comment]
Previous issue also here: https://github.com/objection-lol/issues/issues/40
