### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Cl0ckHvH** [objection-lol/issues#44]
I found bug while using Text Color
![ezgif-3-5b5bb5acf5c5](https://user-images.githubusercontent.com/62774712/97118809-e4c78d80-1714-11eb-86c7-7e88293ad85d.gif)

**Comment by objection-lol** [comment]
Hey.
You need to highlight the text that you want to color, then it can surround that selection with the color tag you picked.

**Comment by Cl0ckHvH** [comment]
Oh, it's working, thanks
