### ISSUE TITLE
Speech bubbles not working? 

### ISSUE THREAD

**Issue by TheD0ct0r101** [objection-lol/issues#46]
Im trying to use the "Hold It" and "Take that" popups for some of my frames, but they only seem to work when im previewing the single individual frame containing the speech bubble. Previewing the full video or exporting it does not show speech bubbles at all.

**Comment by objection-lol** [comment]
Hello.
A character cannot use a speech bubble against itself, this is an automatic behavior, if you change the character or flip it the speech bubble will show.

**Comment by TheD0ct0r101** [comment]
Makes sense. Thank you
