### ISSUE TITLE
Login into other person account

### ISSUE THREAD

**Issue by UNordicc** [objection-lol/issues#48]
After login option has been added, there is a bug that allows to login into person account called "Jotaro".
Bug is super easy to make so this need be fixed.

Login into own account: 
![image](https://user-images.githubusercontent.com/73536467/97305840-e94b8d80-185d-11eb-883e-1fbcdfea6064.png)

Account name preview:
![image](https://user-images.githubusercontent.com/73536467/97305946-0c763d00-185e-11eb-8db7-856b15ffff9e.png)

After pressing back button you getting login into "Jotaro" account:
![image](https://user-images.githubusercontent.com/73536467/97306016-23b52a80-185e-11eb-8d6f-ecd695cf673d.png)

**Comment by objection-lol** [comment]
![Uploading image.png…]()

**Comment by objection-lol** [comment]
![image](https://user-images.githubusercontent.com/71948517/97309519-2f5f1c00-1873-11eb-84ef-411b905efd4a.png)

**Comment by objection-lol** [comment]
Seriously though, it didn't work for me when I tried it.

**Comment by UNordicc** [comment]
I dunno maybe works on Twitter login 🤷‍♂️

**Comment by UNordicc** [comment]
For proof I make screenshots of my and "Jotaro" account
"Jotaro" account: ![unknown-10.png](https://user-images.githubusercontent.com/73536467/97311446-a5a85200-1864-11eb-8a0d-48d2a12d2673.png)
My account: ![Screenshot_20201027_145551_com.android.chrome.jpg](https://user-images.githubusercontent.com/73536467/97311473-afca5080-1864-11eb-9bd7-b1f20c570d95.jpg)


Also I test on Android Chrome and also bug worked ![Screenshot_20201027_145556_com.android.chrome.jpg](https://user-images.githubusercontent.com/73536467/97311530-be186c80-1864-11eb-93a8-a6d171cf84bc.jpg)

**Comment by UNordicc** [comment]
Ok I find out what is making this bug. After auth of the Twitter, website (objection.lol) is making link that login via Twitter, after enter that link second time you getting login into "Jotaro" account

**Comment by UNordicc** [comment]
https://youtu.be/vMGT9S8QFQg

**Comment by objection-lol** [comment]
Thank you, will delete the issue to reduce the impact of the bug.
