### ISSUE TITLE
Black image

### ISSUE THREAD

**Issue by GageE6at** [objection-lol/issues#49]
when i export my objection, in a movie (mp4) on full screen proofs a black screen instead of a picture! I ask to fix it

**Comment by objection-lol** [comment]
Hey. What is the objection URL?

**Comment by GageE6at** [comment]
Take That! https://objection.lol/objection/622682

**Comment by GageE6at** [comment]
Oh, im idiot thats image is too high

**Comment by objection-lol** [comment]
The image is no longer accessible like it was deleted or renamed, that's the reason.
