### ISSUE TITLE
Testimony and Argument animations

### ISSUE THREAD

**Issue by Cl0ckHvH** [objection-lol/issues#50]
It would be cool to put of Witness Testimony, Cross Examination and Rebuttal animations to maker
![Witness](https://user-images.githubusercontent.com/62774712/97331453-127e1500-1882-11eb-973c-cceb499886bb.gif)
![Cross](https://user-images.githubusercontent.com/62774712/97331471-1742c900-1882-11eb-9d07-a6eb8f23a0d2.gif)
![Test](https://user-images.githubusercontent.com/62774712/97331479-190c8c80-1882-11eb-9d14-71d334e8ba3e.gif)
![Argument](https://user-images.githubusercontent.com/62774712/97331491-1b6ee680-1882-11eb-85a7-c8eb53921601.png)
![Rebbutal](https://user-images.githubusercontent.com/62774712/97331496-1ca01380-1882-11eb-8cc7-99ead522d28e.png)

**Comment by objection-lol** [comment]
This has been implemented, although some popups are missing, they will be added when available.
