### ISSUE TITLE
Adding Evidence.

### ISSUE THREAD

**Issue by Winslow08** [objection-lol/issues#52]
Whenever I try adding evidence (On Mobile) it keeps saying invalid file type. Mabye I'm doing something wrong but I thought to add evidence you make an Imgur post, copy the link, and paste it.
Any help at all would be appreciated :)

**Comment by objection-lol** [comment]
Make sure the URL is a direct link, it's direct if you open the link and only the image shows up, but if a website loads with the image then it is not a direct link.

Example of direct link: https://i.postimg.cc/85tjtLGj/Phoenix-Wright-Trilogy-Art-0.png
Example of not a direct link: https://postimg.cc/BLPSvLX0

You can use https://postimages.org/ they show you the direct link after uploading your image.

**Comment by Winslow08** [comment]
Thank you. You're a saviour :)
