### ISSUE TITLE
Incorrectly adding frames

### ISSUE THREAD

**Issue by sonicfind** [objection-lol/issues#53]
If you press the very first add frame button on a page other than page 1,
![image](https://user-images.githubusercontent.com/52436993/97792142-533e9c80-1ba8-11eb-8ec2-99c727db1239.png)
instead of adding a new frame to the top of the current page, it'll add one to the very beginning on the objection.
![image](https://user-images.githubusercontent.com/52436993/97792152-779a7900-1ba8-11eb-9959-b7f71f455483.png)
![image](https://user-images.githubusercontent.com/52436993/97792153-7f5a1d80-1ba8-11eb-8a93-d8cb0f3ed3c0.png)

**Comment by objection-lol** [comment]
Solved.
