### ISSUE TITLE
Issue with Exporting

### ISSUE THREAD

**Issue by FactuallyAccuratePtero** [objection-lol/issues#54]
I don't really know much about programming, but I wanted to say that there's an export thing happening where my project caps at 7 minutes and 3 seconds. The project is about 9 minutes and may put a bit of strain on the site, so that's understandable. Also, whenever I use a screen recorder, everything on the site is black and I only hear audio. This isn't just one screen recorder, this is all of them. May just be an issue on my end, don't really know. Edit: Nevermind, I was being dumb, my bad

**Comment by objection-lol** [comment]
Responding on Email.
