### ISSUE TITLE
Queue

### ISSUE THREAD

**Issue by PhoenixRight** [objection-lol/issues#55]
Hello, dear developers!
You wrote on Twitter that you created a separate server for export, but I have a queue. 
![IMG_20201102_231531](https://user-images.githubusercontent.com/73066569/97920312-f1c22d80-1d61-11eb-8e2a-4504949d885e.png)

**Comment by objection-lol** [comment]
There was a problem with the export servers, it has been sorted. Though, as a side note, if there is a huge number of requests then a queue like this would still happen, maybe not now, but possible. Thank you for reporting.
