### ISSUE TITLE
Apollo Justice

### ISSUE THREAD

**Issue by 11Amigo** [objection-lol/issues#57]
Apollo Justice's model is not HD.

**Comment by objection-lol** [comment]
Please read the sticky to know which characters will be added. Apollo HD is one of them.

**Comment by PhoenixRight** [comment]
> Apollo Justice's model is not HD.

You really dumbass, Apollo will be in HD in the next update

**Comment by 11Amigo** [comment]
Ok ok sorry for everything i was just new to this git hub
