### ISSUE TITLE
Sharper Sounding Objections

### ISSUE THREAD

**Issue by MauroPeos** [objection-lol/issues#59]
[2020-11-08 20-55-45.zip](https://github.com/objection-lol/issues/files/5507058/2020-11-08.20-55-45.zip)
Is there a way to make the objections and the yell backround noise to them sound more sharper like this clip i took?
ive recreated the entire scene and edgeworth's objection doesn't sound as sharp and loud
https://objection.lol/objection/673832

**Comment by PhoenixRight** [comment]
Only you have that problem

**Comment by objection-lol** [comment]
Hi,
This is current sound: https://vocaroo.com/1b5UWrMJb9dt
This is from the Trilogy HD: https://vocaroo.com/13czRx5VTUph

It will be considered to replace them all with the Trilogy ones, though that's not a high priority right now.

**Comment by MauroPeos** [comment]
thank you for taking the time to reply,you can close this issue any time you want

**Comment by MauroPeos** [comment]
about the bubble's animation? is it going to be replaced too?

**Comment by objection-lol** [comment]
We don't have the animation for them.

**Comment by objection-lol** [comment]
This has been done.
