### ISSUE TITLE
a bit of apollo's animations are buggy

### ISSUE THREAD

**Issue by OMGABACON** [objection-lol/issues#62]
![20201109_112526](https://user-images.githubusercontent.com/73717252/98517185-92db4780-227e-11eb-90b8-6f94a8c3a7b2.png)
![20201109_112454](https://user-images.githubusercontent.com/73717252/98517201-966ece80-227e-11eb-9d60-731ff510fdab.png)
![20201109_112421](https://user-images.githubusercontent.com/73717252/98517216-9a025580-227e-11eb-9d9d-ff66125665dc.png)
![20201109_112637](https://user-images.githubusercontent.com/73717252/98517225-9e2e7300-227e-11eb-8ae0-77d1d555cc63.png)

**Comment by OMGABACON** [comment]
also, happened in courtroom

**Comment by objection-lol** [comment]
These look like the old sprites before Apollo was made HD, it's probably cached in your browser, could you try Incognito mode?

**Comment by OMGABACON** [comment]
yeah thanks, it works now
