### ISSUE TITLE
A few important suggestions

### ISSUE THREAD

**Issue by wildcat471** [objection-lol/issues#64]
First and most important, the "NOT GUILTY" popup. I don't know why there's a guilty one and not a not guilty one. Second, the ability to change courtrooms from the original and newer one to make the new characters be able to be integrated in with the old ones. Third and least important, a "Eureka!" speech bubble for Edgeworth, a "Gotcha!" one for Apollo, and maybe a "Welcome!" one for Phoenix (from Professor Layton v Phoenix Wright). Thank you! I've been waiting for the not guilty one for quite some time, I hope it comes soom.

**Comment by objection-lol** [comment]
"Not guilty" has been added yesterday.

**Comment by wildcat471** [comment]
One more thing: The judge's gavel slams seem to be their non-HD versions instead of their HD ones, and it makes it look inconsistent. Thank you!

**Comment by TalesSouzones** [comment]
> "Not guilty" has been added yesterday.

hey,where is the not guilty option?

**Comment by wildcat471** [comment]
> > "Not guilty" has been added yesterday.
> 
> hey,where is the not guilty option?

In the "Frame Options" menu under popups

**Comment by aladairmaxwell** [comment]
I forgot my password. I was wondering why I can't restore it? Will this feature come later or I don't understand something?

**Comment by objection-lol** [comment]
> I forgot my password. I was wondering why I can't restore it? Will this feature come later or I don't understand something?

It will be added next update.
Apollo now has Gotcha and Edgeworth has Eureka.
