### ISSUE TITLE
Backgrounds

### ISSUE THREAD

**Issue by RichardWell56** [objection-lol/issues#69]
Hello! I found some HD backgrounds for the future:
![bg0e9u](https://user-images.githubusercontent.com/73120927/98809776-cf49a780-2426-11eb-8f17-13dcf321da28.png)
![bg001](https://user-images.githubusercontent.com/73120927/98809823-dffa1d80-2426-11eb-86ed-cc2d82efdda6.png)
![bg01e](https://user-images.githubusercontent.com/73120927/98809842-e7b9c200-2426-11eb-8738-c987de4f7bc5.png)
![bg01ff](https://user-images.githubusercontent.com/73120927/98809860-ee483980-2426-11eb-92ae-396816a4fff2.png)
![bg04fu](https://user-images.githubusercontent.com/73120927/98809877-f7d1a180-2426-11eb-8fce-06e714ee9a67.png)
![bg027](https://user-images.githubusercontent.com/73120927/98809899-ff914600-2426-11eb-8c90-11ccd96d1351.png)
![bg050](https://user-images.githubusercontent.com/73120927/98809917-05872700-2427-11eb-9a79-90266ee18138.png)
![bg072f](https://user-images.githubusercontent.com/73120927/98809935-0b7d0800-2427-11eb-96ea-e86e25b4617c.png)
![bg073](https://user-images.githubusercontent.com/73120927/98809950-12a41600-2427-11eb-8846-9cd042b99e76.png)

**Comment by objection-lol** [comment]
Hello. We have all the backgrounds already.
