### ISSUE TITLE
Luke Atmey don't move

### ISSUE THREAD

**Issue by Pelmeno** [objection-lol/issues#7]
![2issue3](https://user-images.githubusercontent.com/73017018/96333268-990c4880-1071-11eb-9a95-5dac1480833b.png)

In a breakdown, the Luke should rise from the bottom when shaking, but it is stuck in place and shakes. (sorry for the mistakes, I used Google translate)

**Comment by objection-lol** [comment]
Resolved. He should move now, re-open if not.
