### ISSUE TITLE
Courtroom not working.

### ISSUE THREAD

**Issue by FugginDumb** [objection-lol/issues#70]
I was attempting to use the Courtroom feature on Objection.lol, but I ran into a little problem. Whether I make or join a courtroom, The room is pitch black, and I can't see anyone in it. I can still choose my characters, type stuff, and choose expressions, though. Could someone help me figure out what's wrong?

**Comment by FugginDumb** [comment]
![image](https://user-images.githubusercontent.com/74313644/98834823-a49f2500-240d-11eb-867f-40396ada0486.png)
Screenshot of problem

**Comment by objection-lol** [comment]
It looks like an extension is blocking the connection, it might be that shield icon at top right corner.

**Comment by FugginDumb** [comment]
I tried that already in an incognito tab. The problem still persisted, though.

**Comment by objection-lol** [comment]
It's possible that an extension is still allowed to run in incognito mode.
Could you try on your phone? It could be that port 9005 is blocked on your network.

**Comment by FugginDumb** [comment]
Oh, nevermind, the problem apparently fixed itself??
I don't seem to be having difficulties with it anymore
Sorry for the minor inconvenience
