### ISSUE TITLE
Game OST Suggestion

### ISSUE THREAD

**Issue by KINGOFPANCAKES** [objection-lol/issues#75]
[**Suggestion**] I was wondering if we have any music files Ripped straight From the Ace Attorney games that aren't in Objection.lol could we post those files here?
Cause I have some from The Great Ace Attorney.

**Comment by objection-lol** [comment]
Hello.
You can add them as custom music, we don't have the loop points data for The Great Ace Attorney, if you are logged in it's even better because the music will be attached to your account and you can use them anytime without having to add a URL again.

**Comment by KINGOFPANCAKES** [comment]
Ah ok thanks for the insight
