### ISSUE TITLE
A question about the Objection Maker.

### ISSUE THREAD

**Issue by NextImBlack** [objection-lol/issues#76]
Hello,
I would like to make a black screen to begin a court session with the Typewriter effect, I found it, but I don't understand how to make the black screen and while on it, write a text.

Kind regards.

**Comment by RichardWell56** [comment]
You can use this link and insert in evidence: https://i.ibb.co/rcy9TGg/6-20201113121854.png

**Comment by NextImBlack** [comment]
Thank you so much. :)

**Comment by Tanjim-Fuad-Arik** [comment]
> Thank you so much. :)
> Also, I got another question: How can I break lines in a text? Because, if I press SHIFT+ENTER, it doesn't work.

That don't work 👍

**Comment by NextImBlack** [comment]
> > Thank you so much. :)
> > Also, I got another question: How can I break lines in a text? Because, if I press SHIFT+ENTER, it doesn't work.
> 
> That don't work :(

Oh... I see. That's sad. :(
Well, anyway, I hope it will added. Many thanks to both of you guys for helping. ❤️

**Comment by objection-lol** [comment]
It seems this has been answered.
