### ISSUE TITLE
[Suggestion] Image system

### ISSUE THREAD

**Issue by Tanjim-Fuad-Arik** [objection-lol/issues#78]
Hello, Developers!

So, by Image System I want to say that make a system where people can take image of a specific part of an objection.
Sometimes, people want to take the picture of a objection,, to make memes. not the entire video. So please add it.

Thanks!...

by the way if you add it. You can also add an image gallary of every image taken in objection.lol

**Comment by objection-lol** [comment]
You can use Greenshot to take a screenshot of your screen, it freezes the screen while you select the region.
https://getgreenshot.org/
By setting a keyboard shortcut in Preferences it's easy to get the part you want:
![image](https://user-images.githubusercontent.com/71948517/99131805-2026ef00-2625-11eb-93df-b294fa3a1f9b.png)

If we ever get a storage server, we can implement that, for now, we can't.

**Comment by Tanjim-Fuad-Arik** [comment]
Thanks

**Comment by Tanjim-Fuad-Arik** [comment]
Thanks
