### ISSUE TITLE
Objection maker fail

### ISSUE THREAD

**Issue by edjooj** [objection-lol/issues#8]
fail to submit
![image](https://user-images.githubusercontent.com/73020114/96334632-947f6a00-1048-11eb-88ec-1fa2eaea71da.png)

**Comment by objection-lol** [comment]
Could you save and attach the save file here?

**Comment by edjooj** [comment]
> Could you save and attach the save file here?

Fine

https://cdn.discordapp.com/attachments/273242877814112267/767074606199603240/My_Objection_1.objection

**Comment by objection-lol** [comment]
Resolved.
