### ISSUE TITLE
Пользовательская Музыка

### ISSUE THREAD

**Issue by PhoenixAlwaysRight** [objection-lol/issues#81]
Здравствуйте, я бы хотел спросить а какой именно формат пользовательской музыки блин поддерживается? Какой URL, какое имя блин надо сделать, чтобы музыка добавилась???
Я пытался вставить из источника YouTube, и из других но не выходит! Подскажите что делать

**Comment by objection-lol** [comment]
Hello.
Try uploading it to Discord then copy the link,
Or you can upload it to Vocaroo and right-click the download button and copy the link.

**Comment by PhoenixAlwaysRight** [comment]
> Привет.
> Попробуйте загрузить его в Discord, а затем скопируйте ссылку,
> Или вы можете загрузить его в Vocaroo и щелкнуть правой кнопкой мыши на кнопке загрузки и скопировать ссылку.

Спасибо!
