### ISSUE TITLE
Preset music unavailable on mobile

### ISSUE THREAD

**Issue by Paragon7667** [objection-lol/issues#82]
![Screenshot_20201117-234857_Chrome](https://user-images.githubusercontent.com/74631123/99464224-86668700-292f-11eb-9bb6-beb6a39c157f.jpg)
![Screenshot_20201117-234903_Chrome](https://user-images.githubusercontent.com/74631123/99464229-89fa0e00-292f-11eb-9056-c4b167e2dd7f.jpg)

**Comment by objection-lol** [comment]
Could you try reloading the page?

**Comment by Paragon7667** [comment]
> Could you try reloading the page?

it appears to be working now
