### ISSUE TITLE
Portsman sprites

### ISSUE THREAD

**Issue by WaluigiPie** [objection-lol/issues#87]
![Makoto-sad%28c%29](https://user-images.githubusercontent.com/64218716/99697388-c13bfc80-2aa0-11eb-8a68-e7a4de401fdc.gif)
![Portsman_Angry_1](https://user-images.githubusercontent.com/64218716/99697393-c1d49300-2aa0-11eb-9179-c1df13b2e4e9.gif)
![Portsman_Angry_2](https://user-images.githubusercontent.com/64218716/99697400-c305c000-2aa0-11eb-9134-6be0825c1edd.gif)
![Portsman_Arm_Up_1](https://user-images.githubusercontent.com/64218716/99697404-c39e5680-2aa0-11eb-87d2-af9e94517cb6.gif)
![Portsman_Arm_Up_2](https://user-images.githubusercontent.com/64218716/99697405-c436ed00-2aa0-11eb-9c2e-3ce348bed05f.gif)
![Portsman_Breakdown](https://user-images.githubusercontent.com/64218716/99697410-c4cf8380-2aa0-11eb-9bdf-449060cfd998.gif)
![Portsman_Coat_1](https://user-images.githubusercontent.com/64218716/99697414-c600b080-2aa0-11eb-8857-7a69e77cdba4.gif)
![Portsman_Coat_2](https://user-images.githubusercontent.com/64218716/99697416-c6994700-2aa0-11eb-9aa9-87cb9ac9da8b.gif)
![Portsman_Coat_Off](https://user-images.githubusercontent.com/64218716/99697421-c731dd80-2aa0-11eb-9f52-00ccd6b97b65.gif)
![Portsman_Coat_On](https://user-images.githubusercontent.com/64218716/99697422-c7ca7400-2aa0-11eb-8046-a9f35c58a84c.gif)
![Portsman_Normal_1](https://user-images.githubusercontent.com/64218716/99697425-c8630a80-2aa0-11eb-98c7-f6c5d10011a0.gif)
![Portsman_Normal_2](https://user-images.githubusercontent.com/64218716/99697426-c8630a80-2aa0-11eb-924f-a5d5238fc26a.gif)
![Screenshot_44-removebg-preview](https://user-images.githubusercontent.com/64218716/99697429-c8fba100-2aa0-11eb-860e-cd8934cab514.png)
![Portsman_Open_Coat_1](https://user-images.githubusercontent.com/64218716/99697430-c9943780-2aa0-11eb-8c67-b4d2b83a7a32.gif)
![Portsman_Open_Coat_2](https://user-images.githubusercontent.com/64218716/99697431-c9943780-2aa0-11eb-9be9-51f8a6756f8e.gif)
![Portsman_Sad_2](https://user-images.githubusercontent.com/64218716/99697432-c9943780-2aa0-11eb-9632-972306c52c36.gif)
![Portsman_Shocked](https://user-images.githubusercontent.com/64218716/99697434-ca2cce00-2aa0-11eb-88e6-17e8f9aa7b1d.gif)
![Portsman_Sweating_1](https://user-images.githubusercontent.com/64218716/99697438-ca2cce00-2aa0-11eb-93e1-906cedd2491a.gif)
![Portsman_Sweating_2](https://user-images.githubusercontent.com/64218716/99697439-cac56480-2aa0-11eb-9eaa-53a5d42e3b3f.gif)
![Portsman_Thumbs_Up_1](https://user-images.githubusercontent.com/64218716/99697444-cb5dfb00-2aa0-11eb-995d-bffed1f3b725.gif)
![Portsman_Thumbs_Up_2](https://user-images.githubusercontent.com/64218716/99697445-cbf69180-2aa0-11eb-98d9-2a768a246b71.gif)
![Portsman_Worried_1](https://user-images.githubusercontent.com/64218716/99697449-cd27be80-2aa0-11eb-807e-95c898b3f260.gif)
![Portsman_Worried_2](https://user-images.githubusercontent.com/64218716/99697453-ce58eb80-2aa0-11eb-80cb-37965b76f3af.gif)

I am pretty sure Investigations sprites can be used with Prosecutor desks + with the new custom BGs feature it can be used even better.

It is just a question but did you think about adding the Investigations popups?

**Comment by PhoenixRight** [comment]
Dude, this is pixel sprites.

**Comment by beeflol** [comment]
Bro, use the pinned comment yo suggest characters.

**Comment by objection-lol** [comment]
As said above, this won't do.
