### ISSUE TITLE
Make Super Objection more accurate

### ISSUE THREAD

**Issue by PavelChitaylo** [objection-lol/issues#89]
Hello there. I've noticed that Phoenix's "Super Objection" emote is not quite accurate.
1. According to the reference [here](https://youtu.be/05kqbH65E70) , Mia must not look taller than Phoenix in this scene. BTW, according to the official guidebooks, Phoenix is 176 cm (5'9") tall, while Mia is 168 cm (5'6") tall.
2. Mia is also semi-transparent in this scene (for she is a ghost or a spirit)
3. Phoenix and Mia yelling "Objection!" together here indeed sound cool, but it isn't accurate to the game.
I'd be glad to see this issue fixed.

**Comment by objection-lol** [comment]
Hi,
Unfortunately, we don't have the in-game animation for it.

**Comment by PavelChitaylo** [comment]
1. I don't think it would be quite hard to edit. Mia's sprite seems to be the same but half-transparent. 
2. The sprites can be found here. https://www.spriters-resource.com/3ds/phoenixwrightaceattorneytrilogy/sheet/67112/

**Comment by Spelunkaria** [comment]
Hey!
For number 1, I'd say the animation for it is good considering it's based on the HD trilogy.
For number 2, semi transparency doesn't work on gifs

**Comment by PavelChitaylo** [comment]
Well then, I have nothing to add
