### ISSUE TITLE
Bug with Judges

### ISSUE THREAD

**Issue by Cl0ckHvH** [objection-lol/issues#90]
After new update, the Judges have bug in "Headshake" animation. In game, they headshaking only one times
![Record_2020-11-21-22-00-18](https://user-images.githubusercontent.com/62774712/99886539-fb92ce80-2c45-11eb-9ee8-16bd9b29fbfa.gif)

**Comment by objection-lol** [comment]
Hi,
This is intended, the "headshake" emotes are new, the previous "negative" emote is still there.
You can see here its used in-game: https://www.youtube.com/watch?v=PWnN-nE9zI0

**Comment by Cl0ckHvH** [comment]
I mean make as "Positive" animation, because not every Headshake is twice or third, or more times

**Comment by objection-lol** [comment]
You can use the "negative" animation to headshake only once.

**Comment by Cl0ckHvH** [comment]
Hmm, okay, i saw this and understood You, thanks
