### ISSUE TITLE
New question

### ISSUE THREAD

**Issue by Audacity0001** [objection-lol/issues#91]
Hello! 
I would like to ask a few questions about the Objection and Yell effect for Phoenix Wright: 

Is there a way to combine both effects at once? To be more understandable, in the real game, when you present proof while you're doing a Cross-Examination, the Yell effects appear along with the Objection popup, and I would like to reproduce it; is there a way to do so? 

Please let me know, thank you so much c:

**Comment by objection-lol** [comment]
Not sure what do you mean, but you can select "Objection!" as a speech bubble and it will automatically play both the sound effect and the popup.

**Comment by NextImBlack** [comment]
Gonna record a clip when I find this "animation".

**Comment by Spelunkaria** [comment]
It can be found here!
![Screenshot_482](https://user-images.githubusercontent.com/74856983/99900789-169b2800-2cb2-11eb-9bc1-c570b3e02b23.png)

**Comment by Audacity0001** [comment]
Yup, I was going to reproduce the objection animation with the Yell one.
