### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Audacity0001** [objection-lol/issues#94]
Hey!
This is not an issue, but a nice suggestion. 

What I wanna suggest is the Court Record feature. Through a new button, you may choose between 6 actions: 

1: Open Court Record 
2: Submit evidence in Court Record (Maybe with the External link system?)
3: Remove evidence in Court Record 
4: Update evidence in Court Record
5: Object with an item in the court record
6: See more informations for an item. 

When you upload evidence in the Court Record, you must set: The name, a short description and who gave it.

**Comment by objection-lol** [comment]
Hi,
That feature is for a case maker, our website is only a "scene maker" that has a playback or a video, there is no interaction between the viewer and the playback like a case maker would provide.
If you mean its for courtroom then you can already do most of these in the Evidence tab.

**Comment by Audacity0001** [comment]
I see, thank you for the clarification. 😄
