### ISSUE TITLE
Android app for creating objections | Android приложение для создания споров

### ISSUE THREAD

**Issue by SpeedRaser1** [objection-lol/issues#95]
**English**: Hello, dear developers!
Is it possible to make the Android application for convenient work with your phone? Which will repeat the functionality of the site, in case it is uncomfortable to work with the mobile version in the browser.
**Russian**: Здравствуйте уважаемые разработчики! 
Возможно ли сделать Android приложение для удобной работы с objection.lol на телефоне? Которое будет повторять функционал сайта, в случае если с ним неудобно работать на мобильной версии в браузере.

**Comment by objection-lol** [comment]
Sorry but there won't be an app, this Issues section is for the website.
